//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo_forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo_forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new task.
        /// </summary>
        internal static string Addanewtask {
            get {
                return ResourceManager.GetString("Addanewtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all tasks.
        /// </summary>
        internal static string Clearalltasks {
            get {
                return ResourceManager.GetString("Clearalltasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all tasks.
        /// </summary>
        internal static string ClearTasks {
            get {
                return ResourceManager.GetString("ClearTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all tasks?.
        /// </summary>
        internal static string ConfirmClearTasks {
            get {
                return ResourceManager.GetString("ConfirmClearTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        internal static string ConfirmDeleteTask {
            get {
                return ResourceManager.GetString("ConfirmDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete task.
        /// </summary>
        internal static string DeleteTask {
            get {
                return ResourceManager.GetString("DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected task.
        /// </summary>
        internal static string Deletetheselectedtask {
            get {
                return ResourceManager.GetString("Deletetheselectedtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        internal static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task.
        /// </summary>
        internal static string Edittask {
            get {
                return ResourceManager.GetString("Edittask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected task.
        /// </summary>
        internal static string Edittheselectedtask {
            get {
                return ResourceManager.GetString("Edittheselectedtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category.
        /// </summary>
        internal static string EnterCategory {
            get {
                return ResourceManager.GetString("EnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new task category.
        /// </summary>
        internal static string EnterNewTaskCategory {
            get {
                return ResourceManager.GetString("EnterNewTaskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit task, Enter new task description.
        /// </summary>
        internal static string EnterNewTaskDescription {
            get {
                return ResourceManager.GetString("EnterNewTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task category.
        /// </summary>
        internal static string EnterTaskCategory {
            get {
                return ResourceManager.GetString("EnterTaskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter task description.
        /// </summary>
        internal static string EnterTaskDescription {
            get {
                return ResourceManager.GetString("EnterTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter time.
        /// </summary>
        internal static string EnterTime {
            get {
                return ResourceManager.GetString("EnterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading tasks. .
        /// </summary>
        internal static string ErrorLoadingTasks {
            get {
                return ResourceManager.GetString("ErrorLoadingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading tasks. See console for details. .
        /// </summary>
        internal static string ErrorLoadingTasks2 {
            get {
                return ResourceManager.GetString("ErrorLoadingTasks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving tasks. .
        /// </summary>
        internal static string ErrorSavingTasks {
            get {
                return ResourceManager.GetString("ErrorSavingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving tasks. See console for details. .
        /// </summary>
        internal static string ErrorSavingTasks2 {
            get {
                return ResourceManager.GetString("ErrorSavingTasks2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        internal static string TaskApp {
            get {
                return ResourceManager.GetString("TaskApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string TaskCategory {
            get {
                return ResourceManager.GetString("TaskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        internal static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task time.
        /// </summary>
        internal static string TaskDue {
            get {
                return ResourceManager.GetString("TaskDue", resourceCulture);
            }
        }
    }
}
